In [1]:
import pandas as pd

dic=pd.read_csv('IpAddress_to_Country.csv')
data=pd.read_csv('Fraud_Data.csv')
dic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138846 entries, 0 to 138845
Data columns (total 3 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   lower_bound_ip_address  138846 non-null  float64
 1   upper_bound_ip_address  138846 non-null  int64  
 2   country                 138846 non-null  object 
dtypes: float64(1), int64(1), object(1)
memory usage: 3.2+ MB


In [12]:
dic.lower_bound_ip_address=dic.lower_bound_ip_address.astype(int)
dic.upper_bound_ip_address=dic.upper_bound_ip_address.astype(int)
dic.sort_values(by=['lower_bound_ip_address'])

lower_bound_ip_address  upper_bound_ip_address    country
0                     16777216                16777471  Australia
1                     16777472                16777727      China
2                     16777728                16778239      China
3                     16778240                16779263  Australia
4                     16779264                16781311      China
...                        ...                     ...        ...
138841              3758092288              3758093311  Hong Kong
138842              3758093312              3758094335      India
138843              3758095360              3758095871      China
138844              3758095872              3758096127  Singapore
138845              3758096128              3758096383  Australia

[138846 rows x 3 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151112 entries, 0 to 151111
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   user_id         151112 non-null  int64  
 1   signup_time     151112 non-null  object 
 2   purchase_time   151112 non-null  object 
 3   purchase_value  151112 non-null  int64  
 4   device_id       151112 non-null  object 
 5   source          151112 non-null  object 
 6   browser         151112 non-null  object 
 7   sex             151112 non-null  object 
 8   age             151112 non-null  int64  
 9   ip_address      151112 non-null  float64
 10  class           151112 non-null  int64  
dtypes: float64(1), int64(4), object(6)
memory usage: 12.7+ MB


In [4]:
data.head()

user_id          signup_time        purchase_time  purchase_value  \
0    22058  2015-02-24 22:55:49  2015-04-18 02:47:11              34   
1   333320  2015-06-07 20:39:50  2015-06-08 01:38:54              16   
2     1359  2015-01-01 18:52:44  2015-01-01 18:52:45              15   
3   150084  2015-04-28 21:13:25  2015-05-04 13:54:50              44   
4   221365  2015-07-21 07:09:52  2015-09-09 18:40:53              39   

       device_id source browser sex  age    ip_address  class  
0  QVPSPJUOCKZAR    SEO  Chrome   M   39  7.327584e+08      0  
1  EOGFQPIZPYXFZ    Ads  Chrome   F   53  3.503114e+08      0  
2  YSSKYOSJHPPLJ    SEO   Opera   M   53  2.621474e+09      1  
3  ATGTXKYKUDUQN    SEO  Safari   M   41  3.840542e+09      0  
4  NAUITBZFJKHWW    Ads  Safari   M   45  4.155831e+08      0

In [15]:
data.purchase_time=pd.to_datetime(data.purchase_time)
data.signup_time=pd.to_datetime(data.signup_time)
data['date_diff']=data.purchase_time-data.signup_time
data['Min_diff']=data.date_diff.dt.total_seconds()/(60*60)
data.ip_address=data.ip_address.astype(int)

In [16]:
data

user_id         signup_time       purchase_time  purchase_value  \
0         22058 2015-02-24 22:55:49 2015-04-18 02:47:11              34   
1        333320 2015-06-07 20:39:50 2015-06-08 01:38:54              16   
2          1359 2015-01-01 18:52:44 2015-01-01 18:52:45              15   
3        150084 2015-04-28 21:13:25 2015-05-04 13:54:50              44   
4        221365 2015-07-21 07:09:52 2015-09-09 18:40:53              39   
...         ...                 ...                 ...             ...   
151107   345170 2015-01-27 03:03:34 2015-03-29 00:30:47              43   
151108   274471 2015-05-15 17:43:29 2015-05-26 12:24:39              35   
151109   368416 2015-03-03 23:07:31 2015-05-20 07:07:47              40   
151110   207709 2015-07-09 20:06:07 2015-09-07 09:34:46              46   
151111   138208 2015-06-10 07:02:20 2015-07-21 02:03:53              20   

            device_id  source browser sex  age  ip_address  class  \
0       QVPSPJUOCKZAR     SEO  Chrome   M   39   732758368      0   
1       EOGFQPIZPYXFZ     Ads  Chrome   F   53   350311387      0   
2       YSSKYOSJHPPLJ     SEO   Opera   M   53  2621473820      1   
3       ATGTXKYKUDUQN     SEO  Safari   M   41  3840542443      0   
4       NAUITBZFJKHWW     Ads  Safari   M   45   415583117      0   
...               ...     ...     ...  ..  ...         ...    ...   
151107  XPSKTWGPWINLR     SEO  Chrome   M   28  3451154526      1   
151108  LYSFABUCPCGBA     SEO  Safari   M   32  2439047221      0   
151109  MEQHCSJUBRBFE     SEO      IE   F   26  2748470523      0   
151110  CMCXFGRHYSTVJ     SEO  Chrome   M   37  3601174708      0   
151111  ZINIADFCLHYPG  Direct      IE   M   38  4103824510      0   

              date_diff     Min_diff  
0      52 days 03:51:22  1251.856111  
1       0 days 04:59:04     4.984444  
2       0 days 00:00:01     0.000278  
3       5 days 16:41:25   136.690278  
4      50 days 11:31:01  1211.516944  
...                 ...          ...  
151107 60 days 21:27:13  1461.453611  
151108 10 days 18:41:10   258.686111  
151109 77 days 08:00:16  1856.004444  
151110 59 days 13:28:39  1429.477500  
151111 40 days 19:01:33   979.025833  

[151112 rows x 13 columns]

Task 1: For each user, determine her country based on the numeric IP address.

In [17]:
import pandasql as ps

sqlcode = '''
select A.*,B.country
from data A
left join dic B on a.ip_address
between b.lower_bound_ip_address and b.upper_bound_ip_address
'''

new_data = ps.sqldf(sqlcode,locals())


/Users/calili/opt/anaconda3/envs/si649f20/lib/python3.8/site-packages/pandasql/sqldf.py:120: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  to_sql(df, name=tablename, con=conn,


In [26]:
new_data['country']=new_data.country.fillna('Missing')

In [27]:
new_data

user_id                 signup_time               purchase_time  \
0         22058  2015-02-24 22:55:49.000000  2015-04-18 02:47:11.000000   
1        333320  2015-06-07 20:39:50.000000  2015-06-08 01:38:54.000000   
2          1359  2015-01-01 18:52:44.000000  2015-01-01 18:52:45.000000   
3        150084  2015-04-28 21:13:25.000000  2015-05-04 13:54:50.000000   
4        221365  2015-07-21 07:09:52.000000  2015-09-09 18:40:53.000000   
...         ...                         ...                         ...   
151107   345170  2015-01-27 03:03:34.000000  2015-03-29 00:30:47.000000   
151108   274471  2015-05-15 17:43:29.000000  2015-05-26 12:24:39.000000   
151109   368416  2015-03-03 23:07:31.000000  2015-05-20 07:07:47.000000   
151110   207709  2015-07-09 20:06:07.000000  2015-09-07 09:34:46.000000   
151111   138208  2015-06-10 07:02:20.000000  2015-07-21 02:03:53.000000   

        purchase_value      device_id  source browser sex  age  ip_address  \
0                   34  QVPSPJUOCKZAR     SEO  Chrome   M   39   732758368   
1                   16  EOGFQPIZPYXFZ     Ads  Chrome   F   53   350311387   
2                   15  YSSKYOSJHPPLJ     SEO   Opera   M   53  2621473820   
3                   44  ATGTXKYKUDUQN     SEO  Safari   M   41  3840542443   
4                   39  NAUITBZFJKHWW     Ads  Safari   M   45   415583117   
...                ...            ...     ...     ...  ..  ...         ...   
151107              43  XPSKTWGPWINLR     SEO  Chrome   M   28  3451154526   
151108              35  LYSFABUCPCGBA     SEO  Safari   M   32  2439047221   
151109              40  MEQHCSJUBRBFE     SEO      IE   F   26  2748470523   
151110              46  CMCXFGRHYSTVJ     SEO  Chrome   M   37  3601174708   
151111              20  ZINIADFCLHYPG  Direct      IE   M   38  4103824510   

        class         date_diff     Min_diff        country  
0           0  4506682000000000  1251.856111          Japan  
1           0    17944000000000     4.984444  United States  
2           1        1000000000     0.000278  United States  
3           0   492085000000000   136.690278        Missing  
4           0  4361461000000000  1211.516944  United States  
...       ...               ...          ...            ...  
151107      1  5261233000000000  1461.453611  United States  
151108      0   931270000000000   258.686111    Netherlands  
151109      0  6681616000000000  1856.004444          Japan  
151110      0  5146119000000000  1429.477500  United States  
151111      0  3524493000000000   979.025833        Missing  

[151112 rows x 14 columns]

Machine learning model - Logistic regression

In [28]:
from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import train_test_split

x=new_data[['purchase_value','source','browser','sex','age','Min_diff','country']]
x=pd.get_dummies(x)
y=new_data['class'].astype(str)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
lr=LogisticRegressionCV(scoring='roc_auc',max_iter=1000,class_weight='balanced')
lr.fit(x_train,y_train)
lr.score(x_train,y_train)

0.7567001281448535

In [29]:
lr.score(x_test,y_test)

0.7616630224775311

In [30]:
from sklearn.metrics import classification_report,confusion_matrix

ytest_predict = lr.predict(x_test)
print(classification_report(y_true=y_test,y_pred=ytest_predict))

              precision    recall  f1-score   support

           0       0.95      0.64      0.77     41040
           1       0.17      0.71      0.28      4294

    accuracy                           0.65     45334
   macro avg       0.56      0.68      0.52     45334
weighted avg       0.88      0.65      0.72     45334



In [47]:
importance=pd.DataFrame({'var name':x_train.columns,'coef':lr.coef_[0]})
importance['importance']=abs(importance.coef)
importance.sort_values(by=['importance'], ascending=False).head(20)

var name      coef  importance
4             source_Direct  0.163106    0.163106
5                source_SEO -0.069621    0.069621
77          country_Germany -0.057703    0.057703
45           country_Canada  0.056114    0.056114
12                    sex_M  0.052758    0.052758
121         country_Missing -0.052154    0.052154
6            browser_Chrome  0.051647    0.051647
8                browser_IE -0.049162    0.049162
185   country_United States  0.046268    0.046268
7           browser_FireFox  0.046063    0.046063
184  country_United Kingdom  0.033444    0.033444
10           browser_Safari  0.027808    0.027808
134     country_New Zealand  0.027582    0.027582
60          country_Denmark  0.027518    0.027518
11                    sex_F  0.024398    0.024398
170          country_Sweden  0.021296    0.021296
138          country_Norway  0.020358    0.020358
152         country_Romania -0.018380    0.018380
132     country_Netherlands -0.016541    0.016541
3                source_Ads -0.016330    0.016330

important vars:

 source

 country

 sex

 browser

 

Change the cutoff(default at .5)

reference code: https://stackoverflow.com/questions/28716241/controlling-the-threshold-in-logistic-regression-in-scikit-learn

In [46]:
from sklearn.metrics import accuracy_score

pred_proba_df = pd.DataFrame(lr.predict_proba(x_test))
threshold_list = [0.05,0.1,0.15,0.2,0.25,0.3,0.35,0.4,0.45,0.5,0.55,0.6,0.65,.7,.75,.8,.85,.9,.95,.99]
for i in threshold_list:
    print ('\n******** For i = {} ******'.format(i))
    Y_test_pred = pred_proba_df.applymap(lambda x: 1 if x>i else 0)
    test_accuracy = accuracy_score(y_test.astype(int).to_numpy().reshape(y_test.to_numpy().size,1),
                                           Y_test_pred.iloc[:,1].to_numpy().reshape(Y_test_pred.iloc[:,1].to_numpy().size,1))
    print('Our testing accuracy is {}'.format(test_accuracy))

    print(confusion_matrix(y_test.astype(int).to_numpy().reshape(y_test.to_numpy().size,1),
                           Y_test_pred.iloc[:,1].to_numpy().reshape(Y_test_pred.iloc[:,1].to_numpy().size,1)))


******** For i = 0.05 ******
Our testing accuracy is 0.09471919530595138
[[    0 41040]
 [    0  4294]]

******** For i = 0.1 ******
Our testing accuracy is 0.09471919530595138
[[    0 41040]
 [    0  4294]]

******** For i = 0.15 ******
Our testing accuracy is 0.10191026602549963
[[  343 40697]
 [   17  4277]]

******** For i = 0.2 ******
Our testing accuracy is 0.19535006838134733
[[ 4791 36249]
 [  229  4065]]

******** For i = 0.25 ******
Our testing accuracy is 0.2890986897251511
[[ 9264 31776]
 [  452  3842]]

******** For i = 0.3 ******
Our testing accuracy is 0.3751488948691931
[[13344 27696]
 [  631  3663]]

******** For i = 0.35 ******
Our testing accuracy is 0.449375744474346
[[16869 24171]
 [  791  3503]]

******** For i = 0.4 ******
Our testing accuracy is 0.5180659107954295
[[20123 20917]
 [  931  3363]]

******** For i = 0.45 ******
Our testing accuracy is 0.5842634667137248
[[23269 17771]
 [ 1076  3218]]

******** For i = 0.5 ******
Our testing accuracy is 0.6493580976

cutoff at .75 gives us the highest accuracy with the confusion matrix as: 

[[40941    99]
 [ 3946   348]]

However, this cutoff is based off the same weights for the fp and fn. If the weights change, the cutoff also changes.